// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2VeoS3Cx2t2DljAeMRVL7Nu6Q-WFRDW4',
    appId: '1:995953246764:web:b7bbf7b1ece730183bc789',
    messagingSenderId: '995953246764',
    projectId: 'peerview-613f7',
    authDomain: 'peerview-613f7.firebaseapp.com',
    storageBucket: 'peerview-613f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgBLB6c_-s0Kquz_qoNdx4acjsecJjiGA',
    appId: '1:995953246764:android:60b46a240aa832c93bc789',
    messagingSenderId: '995953246764',
    projectId: 'peerview-613f7',
    storageBucket: 'peerview-613f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH_5g3nPn6Ri5IltQgtcipsdpX_bu_rVk',
    appId: '1:995953246764:ios:831a75b01e21f4a83bc789',
    messagingSenderId: '995953246764',
    projectId: 'peerview-613f7',
    storageBucket: 'peerview-613f7.firebasestorage.app',
    iosBundleId: 'com.example.peerview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH_5g3nPn6Ri5IltQgtcipsdpX_bu_rVk',
    appId: '1:995953246764:ios:831a75b01e21f4a83bc789',
    messagingSenderId: '995953246764',
    projectId: 'peerview-613f7',
    storageBucket: 'peerview-613f7.firebasestorage.app',
    iosBundleId: 'com.example.peerview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2VeoS3Cx2t2DljAeMRVL7Nu6Q-WFRDW4',
    appId: '1:995953246764:web:2bc2844f533a34363bc789',
    messagingSenderId: '995953246764',
    projectId: 'peerview-613f7',
    authDomain: 'peerview-613f7.firebaseapp.com',
    storageBucket: 'peerview-613f7.firebasestorage.app',
  );
}
